const data = {
    products: [{
            _id: '1',
            name: 'single back tat',
            category: 'angel',
            image: '/images/pr1.jpg',
            price: '120',
            brand: 'female',
            rating: 4.5,
            numReviews: '10',
            description: 'high quality',
        },
        {
            _id: '2',
            name: 'full tigh tat',
            category: 'animal',
            image: '/images/pr2.jpg',
            price: '121',
            brand: 'ant',
            rating: 4.0,
            numReviews: '11',
            description: 'high quality',
        },
        {
            _id: '3',
            name: 'full back tat',
            category: 'art',
            image: '/images/pr3.jpg',
            price: '122',
            brand: 'fiction',
            rating: 5,
            numReviews: '12',
            description: 'high quality',
        },
        {
            _id: '4',
            name: 'double back tat',
            category: 'angel',
            image: '/images/pr4.jpg',
            price: '124',
            brand: 'female',
            rating: 3.5,
            numReviews: '15',
            description: 'high quality',
        },
        {
            _id: '5',
            name: 'half tigh tat',
            category: 'flower',
            image: '/images/pr5.jpg',
            price: '129',
            brand: 'rose',
            rating: 3,
            numReviews: '20',
            description: 'high quality',
        },
        {
            _id: '6',
            name: 'leg tat',
            category: 'animal',
            image: '/images/pr6.jpg',
            price: '130',
            brand: 'wild',
            rating: 5,
            numReviews: '15',
            description: 'high quality',
        },

    ],
};
export default data;